Controllers/AuthController.cs
using CvAsp2.Models;
using CvAsp2.Tool;
using Microsoft.AspNetCore.Mvc;
using Model_Data_Acces_Layer.Repository;

namespace CvAsp2.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAppUserRepository _repo;
        private readonly SessionManager _sessionManager;

        public AuthController(IAppUserRepository repo, SessionManager sessionManager)
        {
            _repo = repo;
            _sessionManager = sessionManager;
        }

        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Register(RegisterUserForm form)
        {
            if (!ModelState.IsValid) return View(form);

            _repo.Register(form.Email, form.Password);
            return RedirectToAction("Index", "InfoPerso");
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(LoginForm form)
        {
            if (!ModelState.IsValid) return View(form);

            AppUser currentUser = _repo.Login(form.Email, form.Password).ToASP();
            //HttpContext.Session.SetString("ScreenName", currentUser.ScreenName);
            //HttpContext.Session.SetInt32("Id", currentUser.Id);
            _sessionManager.CurrentUser = currentUser;

            return RedirectToAction("Index", "InfoPerso");
        }

        public IActionResult LogOut()
        {
            //HttpContext.Session.Clear();
            _sessionManager.Disconnect();
            return RedirectToAction("Login");
        }
    }
}

Controllers/CompétenceController.cs
using CvAsp2.Models;
using CvAsp2.Tool;
using Microsoft.AspNetCore.Mvc;
using Model_Data_Acces_Layer.Repository;

namespace CvAsp2.Controllers
{
    public class CompétenceController : Controller
    {
        private readonly ICompétenceRepository _repo;

        public CompétenceController(ICompétenceRepository repo)
        {
            _repo = repo;
        }

        public IActionResult Index()
        {
            return View(_repo.GetAll());
        }
        public IActionResult Delete(int id)
        {
            _repo.Delete(id);
            return RedirectToAction("Index");
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CompétenceForm form)
        {
            if (!ModelState.IsValid) return View(form);

            _repo.Create(form.Name);

            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id)
        {
            return View(_repo.GetById(id).ToFormView());
        }
        [HttpPost]
        public IActionResult Edit(CompétenceForm f)
        {
            if (!ModelState.IsValid) return View(f);

            _repo.Update(f.FormToDAL());

            return RedirectToAction("Index");
        }
    }
}

Controllers/ExpérienceController.cs
using CvAsp2.Models;
using CvAsp2.Tool;
using Microsoft.AspNetCore.Mvc;
using Model_Data_Acces_Layer.Repository;

namespace CvAsp2.Controllers
{
    public class ExpérienceController : Controller
    {
        private readonly IExpérienceRepository _service;

        public ExpérienceController(IExpérienceRepository service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View(_service.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }
        public IActionResult Delete(int id)
        {
            _service.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Create(ExpérienceForm form)
        {

            if (!ModelState.IsValid)
            {
                return View(form);
            }

            try
            {
                _service.Create(form.FormToDAL());
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(form);
            }
        }
        public IActionResult Edit(int id)
        {
            return View(_service.GetById(id).ToFormView());
        }
        [HttpPost]
        public IActionResult Edit(ExpérienceForm f)
        {
            if (!ModelState.IsValid) return View(f);

            _service.Update(f.FormToDAL());

            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
 @using CvAsp2.Tool
 @inject SessionManager _session
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CvAsp2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CvAsp2.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">CvAsp</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor02">
      <ul class="navbar-nav me-auto">
       <li class="nav-item">
          <a class="nav-link text-white" asp-area="" asp-controller="InfoPerso" asp-action="Index">Info Personelles</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-white" asp-area="" asp-controller="Compétence" asp-action="Index">Compétences</a>
          </li>
           <li class="nav-item">
              <a class="nav-link text-white" asp-area="" asp-controller="Expérience" asp-action="Index">Expériences</a>
          </li>
          @*@if (@ViewContext.HttpContext.Session.GetString("ScreenName") == null)*@
          @if(_session.CurrentUser is null)
          {
              <li class="nav-item">
                  <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Login">Connexion</a>
              </li>
          }
          else
          {
              <li class="nav-item">
                  <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="LogOut">Déconnexion</a>
              </li>
          }   
      </ul>
    </div>
  </div>
</nav>
       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CvAsp2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/250f73a151.js" crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>